name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: warrenbuckley/Setup-MSBuild@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: msbuild src/WAVE.lib/WAVE.lib.csproj --configuration Release
